# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7a834b364963b7445c0ca0fcb17951b7ea07a89f9c039166e8635e89082c7925bf67531ea9fbf6d70af84ac769e47e2fe7cf4c58b27a5cd150ca4ee89db76fe

test:
  secret_key_base: 447de05f96a2239d46a85eeb83fb2c4214e5e36c0244690206d86c3a08a36d58f370ad5fd9cd89a9b4755aae2b9b764f8102ab53b2beb95300bbe0fa81690384

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
